import { SyllabusItem } from './types';

export const SYLLABUS: SyllabusItem[] = [
  // LÍNGUA PORTUGUESA
  { id: 'lp-1.1', subject: 'Língua Portuguesa', topic: '1 Língua Portuguesa', subtopic: '1.1 Sistema gráfico', description: 'Ortografia, acentuação, pontuação e legibilidade.', incidence: 'Baixa' },
  { id: 'lp-1.2', subject: 'Língua Portuguesa', topic: '1 Língua Portuguesa', subtopic: '1.2 Morfossintaxe', description: 'Estrutura e organização sintática das palavras.', incidence: 'Baixa' },
  { id: 'lp-1.3', subject: 'Língua Portuguesa', topic: '1 Língua Portuguesa', subtopic: '1.3 Semântica', description: 'Significado e interpretação das palavras e frases.', incidence: 'Alta' },
  { id: 'lp-1.4', subject: 'Língua Portuguesa', topic: '1 Língua Portuguesa', subtopic: '1.4 Vocabulário', description: 'Uso e escolha de palavras adequadas.', incidence: 'Baixa' },
  { id: 'lp-2.1', subject: 'Língua Portuguesa', topic: '2 Leitura e Produção de Textos', subtopic: '2.1 Compreensão e análise crítica', description: 'Compreensão e análise de textos escritos.', incidence: 'Alta' },
  { id: 'lp-2.2', subject: 'Língua Portuguesa', topic: '2 Leitura e Produção de Textos', subtopic: '2.2 Linguística, literatura e estilística', description: 'Funções da linguagem, níveis de linguagem e estilo.', incidence: 'Baixa' },
  { id: 'lp-2.3', subject: 'Língua Portuguesa', topic: '2 Leitura e Produção de Textos', subtopic: '2.3 Redação dissertativa', description: 'Fundamentação conceitual e factual, coesão e coerência.', incidence: 'Alta' },
  { id: 'lp-2.3.1', subject: 'Língua Portuguesa', topic: '2 Leitura e Produção de Textos', subtopic: '2.3.1 Defeitos de conteúdo', description: 'Descontextualização, generalização, simplismo e paráfrase.', incidence: 'Alta' },
  { id: 'lp-2.3.2', subject: 'Língua Portuguesa', topic: '2 Leitura e Produção de Textos', subtopic: '2.3.2 Vícios de linguagem e estilo', description: 'Ruptura de registro linguístico e coloquialismos.', incidence: 'Média' },

  // LÍNGUA INGLESA
  { id: 'li-1.1', subject: 'Língua Inglesa', topic: '1 Primeira Fase', subtopic: '1.1 Compreensão de textos', description: 'Compreensão de textos escritos em língua inglesa.', incidence: 'Alta' },
  { id: 'li-1.2', subject: 'Língua Inglesa', topic: '1 Primeira Fase', subtopic: '1.2 Itens gramaticais', description: 'Gramática relevante para compreensão de textos.', incidence: 'Alta' },
  { id: 'li-2.1', subject: 'Língua Inglesa', topic: '2 Segunda Fase', subtopic: '2.1 Redação em língua inglesa', description: 'Expressão em nível avançado e domínio da língua.', incidence: 'Alta' },
  { id: 'li-2.2', subject: 'Língua Inglesa', topic: '2 Segunda Fase', subtopic: '2.2 Resumo', description: 'Capacidade de síntese e respeito ao registro.', incidence: 'Alta' },

  // LÍNGUA FRANCESA
  { id: 'lf-1.1', subject: 'Língua Francesa', topic: '1 Língua Francesa', subtopic: '1.1 Resumo em Francês', description: 'Capacidade de síntese e reelaboração em registro culto.', incidence: 'Alta' },
  { id: 'lf-1.2', subject: 'Língua Francesa', topic: '1 Língua Francesa', subtopic: '1.2 Versão do Português para o Francês', description: 'Fidelidade ao texto-fonte, qualidade e registro.', incidence: 'Alta' },

  // HISTÓRIA DO BRASIL
  { id: 'hb-1.1', subject: 'História do Brasil', topic: '1 Período Colonial', subtopic: '1.1 Configuração territorial', description: 'América Portuguesa: formação territorial.', incidence: 'Média' },
  { id: 'hb-1.2', subject: 'História do Brasil', topic: '1 Período Colonial', subtopic: '1.2 Dimensões econômicas e sociais', description: 'Aspectos econômicos e sociais da América Portuguesa.', incidence: 'Média' },
  { id: 'hb-2.1', subject: 'História do Brasil', topic: '2 Processo de Independência', subtopic: '2.1 Movimentos emancipacionistas', description: 'Movimentos que levaram à independência.', incidence: 'Alta' },
  { id: 'hb-2.2', subject: 'História do Brasil', topic: '2 Processo de Independência', subtopic: '2.2 Situação política e econômica europeia', description: 'Contexto europeu e suas influências.', incidence: 'Alta' },
  { id: 'hb-2.3', subject: 'História do Brasil', topic: '2 Processo de Independência', subtopic: '2.3 Brasil como sede monárquica', description: 'Brasil como sede do Estado português.', incidence: 'Alta' },
  { id: 'hb-2.4', subject: 'História do Brasil', topic: '2 Processo de Independência', subtopic: '2.4 Constitucionalismo português', description: 'Influência do constitucionalismo na independência.', incidence: 'Alta' },
  { id: 'hb-2.5', subject: 'História do Brasil', topic: '2 Processo de Independência', subtopic: '2.5 Ideias liberais', description: 'Repercussão das ideias liberais no Brasil.', incidence: 'Média' },
  { id: 'hb-3.1', subject: 'História do Brasil', topic: '3 Primeiro Reinado (1822-1831)', subtopic: '3.1 Constituição de 1824', description: 'Características e impacto.', incidence: 'Alta' },
  { id: 'hb-3.2', subject: 'História do Brasil', topic: '3 Primeiro Reinado (1822-1831)', subtopic: '3.2 Quadro político interno', description: 'Dinâmicas políticas internas.', incidence: 'Média' },
  { id: 'hb-3.3', subject: 'História do Brasil', topic: '3 Primeiro Reinado (1822-1831)', subtopic: '3.3 Política exterior', description: 'Relações internacionais no período.', incidence: 'Média' },
  { id: 'hb-4.1', subject: 'História do Brasil', topic: '4 Regência (1831-1840)', subtopic: '4.1 Centralização vs. descentralização', description: 'Reformas institucionais.', incidence: 'Alta' },
  { id: 'hb-4.2', subject: 'História do Brasil', topic: '4 Regência (1831-1840)', subtopic: '4.2 Ato Adicional de 1834', description: 'Impactos e revoltas provinciais.', incidence: 'Alta' },
  { id: 'hb-4.3', subject: 'História do Brasil', topic: '4 Regência (1831-1840)', subtopic: '4.3 Dimensão externa', description: 'Política externa da Regência.', incidence: 'Média' },
  { id: 'hb-5.1', subject: 'História do Brasil', topic: '5 Segundo Reinado (1840-1889)', subtopic: '5.1 Estado centralizado', description: 'Mudanças institucionais, partidos políticos.', incidence: 'Alta' },
  { id: 'hb-5.2', subject: 'História do Brasil', topic: '5 Segundo Reinado (1840-1889)', subtopic: '5.2 Política externa', description: 'Relações com Europa, EUA, Reino Unido; Questão Christie; Guerra do Paraguai.', incidence: 'Alta' },
  { id: 'hb-5.3', subject: 'História do Brasil', topic: '5 Segundo Reinado (1840-1889)', subtopic: '5.3 Questão da escravidão', description: 'Debates e impactos.', incidence: 'Alta' },
  { id: 'hb-5.4', subject: 'História do Brasil', topic: '5 Segundo Reinado (1840-1889)', subtopic: '5.4 Crise do Estado Monárquico', description: 'Fatores da crise.', incidence: 'Alta' },
  { id: 'hb-5.5', subject: 'História do Brasil', topic: '5 Segundo Reinado (1840-1889)', subtopic: '5.5 Sociedade e cultura', description: 'População, estrutura social, vida acadêmica.', incidence: 'Alta' },
  { id: 'hb-5.6', subject: 'História do Brasil', topic: '5 Segundo Reinado (1840-1889)', subtopic: '5.6 Economia', description: 'Agroexportação, expansão econômica, ferrovias.', incidence: 'Alta' },
  { id: 'hb-6.1', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.1 Proclamação da República', description: 'Governos militares.', incidence: 'Média' },
  { id: 'hb-6.2', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.2 Constituição de 1891', description: 'Características e impactos.', incidence: 'Média' },
  { id: 'hb-6.3', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.3 Regime oligárquico', description: 'Política dos estados, coronelismo, sistema eleitoral.', incidence: 'Média' },
  { id: 'hb-6.4', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.4 Economia agroexportadora', description: 'Características econômicas.', incidence: 'Média' },
  { id: 'hb-6.5', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.5 Política externa', description: 'Obra de Rio Branco, II Conferência de Haia.', incidence: 'Alta' },
  { id: 'hb-6.6', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.6 Sociedade e cultura', description: 'Modernismo.', incidence: 'Média' },
  { id: 'hb-6.7', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.7 Crise dos anos 20', description: 'Tenentismo e revoltas.', incidence: 'Média' },
  { id: 'hb-6.8', subject: 'História do Brasil', topic: '6 Primeira República (1889-1930)', subtopic: '6.8 Revolução de 1930', description: 'Contexto e consequências.', incidence: 'Média' },
  { id: 'hb-7.1', subject: 'História do Brasil', topic: '7 Era Vargas (1930-1945)', subtopic: '7.1 Processo político e econômico', description: 'Quadro político e financeiro.', incidence: 'Alta' },
  { id: 'hb-7.2', subject: 'História do Brasil', topic: '7 Era Vargas (1930-1945)', subtopic: '7.2 Constituição de 1934', description: 'Características.', incidence: 'Alta' },
  { id: 'hb-7.3', subject: 'História do Brasil', topic: '7 Era Vargas (1930-1945)', subtopic: '7.3 Constituição de 1937', description: 'Estado Novo.', incidence: 'Alta' },
  { id: 'hb-7.4', subject: 'História do Brasil', topic: '7 Era Vargas (1930-1945)', subtopic: '7.4 Contexto internacional', description: 'Brasil na Segunda Guerra Mundial.', incidence: 'Alta' },
  { id: 'hb-7.5', subject: 'História do Brasil', topic: '7 Era Vargas (1930-1945)', subtopic: '7.5 Industrialização e legislação trabalhista', description: 'Avanços e impactos.', incidence: 'Alta' },
  { id: 'hb-7.6', subject: 'História do Brasil', topic: '7 Era Vargas (1930-1945)', subtopic: '7.6 Sociedade e cultura', description: 'Transformações culturais.', incidence: 'Alta' },
  { id: 'hb-8.1', subject: 'História do Brasil', topic: '8 República Liberal (1945-1964)', subtopic: '8.1 Nova ordem política', description: 'Partidos, eleições, Constituição de 1946.', incidence: 'Média' },
  { id: 'hb-8.2', subject: 'História do Brasil', topic: '8 República Liberal (1945-1964)', subtopic: '8.2 Industrialização e urbanização', description: 'Transformações econômicas e sociais.', incidence: 'Média' },
  { id: 'hb-8.3', subject: 'História do Brasil', topic: '8 República Liberal (1945-1964)', subtopic: '8.3 Política externa', description: 'Relações com EUA, Guerra Fria, Operação Pan-Americana.', incidence: 'Alta' },
  { id: 'hb-8.4', subject: 'História do Brasil', topic: '8 República Liberal (1945-1964)', subtopic: '8.4 Sociedade e cultura', description: 'Mudanças culturais.', incidence: 'Média' },
  { id: 'hb-9.1', subject: 'História do Brasil', topic: '9 Regime Militar (1964-1985)', subtopic: '9.1 Constituições de 1967 e 1969', description: 'Características e mudanças.', incidence: 'Média' },
  { id: 'hb-9.2', subject: 'História do Brasil', topic: '9 Regime Militar (1964-1985)', subtopic: '9.2 Economia', description: 'Transformações econômicas.', incidence: 'Média' },
  { id: 'hb-9.3', subject: 'História do Brasil', topic: '9 Regime Militar (1964-1985)', subtopic: '9.3 Política externa', description: 'Relações com EUA, América Latina, África.', incidence: 'Alta' },
  { id: 'hb-9.4', subject: 'História do Brasil', topic: '9 Regime Militar (1964-1985)', subtopic: '9.4 Sociedade e cultura', description: 'Dinâmicas sociais e culturais.', incidence: 'Média' },
  { id: 'hb-9.5', subject: 'História do Brasil', topic: '9 Regime Militar (1964-1985)', subtopic: '9.5 Transição política', description: 'Processo de redemocratização.', incidence: 'Média' },
  { id: 'hb-10.1', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.1 Constituição de 1988', description: 'Características e impactos.', incidence: 'Média' },
  { id: 'hb-10.2', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.2 Partidos e eleições', description: 'Dinâmicas políticas.', incidence: 'Média' },
  { id: 'hb-10.3', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.3 Transformações econômicas', description: 'Mudanças econômicas.', incidence: 'Média' },
  { id: 'hb-10.4', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.4 Impactos da globalização', description: 'Efeitos no Brasil.', incidence: 'Média' },
  { id: 'hb-10.5', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.5 Mudanças sociais', description: 'Transformações sociais.', incidence: 'Média' },
  { id: 'hb-10.6', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.6 Manifestações culturais', description: 'Cultura contemporânea.', incidence: 'Média' },
  { id: 'hb-10.7', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.7 Evolução da política externa', description: 'Diretrizes da política externa.', incidence: 'Alta' },
  { id: 'hb-10.8', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.8 MERCOSUL', description: 'Integração regional.', incidence: 'Alta' },
  { id: 'hb-10.9', subject: 'História do Brasil', topic: '10 Processo Democrático (1985 em diante)', subtopic: '10.9 Brasil na ONU', description: 'Participação internacional.', incidence: 'Alta' },
  { id: 'hb-11', subject: 'História do Brasil', topic: '11 Impactos Tecnológicos e Digitais', subtopic: '11.1 Transformações digitais', description: 'Transformações políticas e sociais no Brasil.', incidence: 'Média' },

  // HISTÓRIA MUNDIAL
  { id: 'hm-1.1', subject: 'História Mundial', topic: '1 Estruturas e Ideias Econômicas', subtopic: '1.1 Revolução Industrial ao capitalismo organizado', description: 'Séculos XVIII a XX.', incidence: 'Alta' },
  { id: 'hm-1.2', subject: 'História Mundial', topic: '1 Estruturas e Ideias Econômicas', subtopic: '1.2 Desenvolvimento capitalista', description: 'Fases desde 1780.', incidence: 'Média' },
  { id: 'hm-1.3', subject: 'História Mundial', topic: '1 Estruturas e Ideias Econômicas', subtopic: '1.3 Ideias econômicas', description: 'Fisiocracia, Liberalismo, Marxismo.', incidence: 'Média' },
  { id: 'hm-1.5', subject: 'História Mundial', topic: '1 Estruturas e Ideias Econômicas', subtopic: '1.5 Crise de 1929 e New Deal', description: 'Mecanismos anticrise.', incidence: 'Alta' },
  { id: 'hm-1.6', subject: 'História Mundial', topic: '1 Estruturas e Ideias Econômicas', subtopic: '1.6 Prosperidade pós-guerra', description: 'Contexto econômico.', incidence: 'Média' },
  { id: 'hm-1.7', subject: 'História Mundial', topic: '1 Estruturas e Ideias Econômicas', subtopic: '1.7 Estado de bem-estar social', description: 'Crise do Welfare State.', incidence: 'Média' },
  { id: 'hm-1.8', subject: 'História Mundial', topic: '1 Estruturas e Ideias Econômicas', subtopic: '1.8 Pós-Fordismo', description: 'Acumulação flexível.', incidence: 'Baixa' },
  { id: 'hm-2.1', subject: 'História Mundial', topic: '2 Revoluções', subtopic: '2.1 Revolução Francesa', description: 'Revoluções burguesas.', incidence: 'Alta' },
  { id: 'hm-2.2', subject: 'História Mundial', topic: '2 Revoluções', subtopic: '2.2 Independência na América', description: 'Processos de independência.', incidence: 'Alta' },
  { id: 'hm-2.3', subject: 'História Mundial', topic: '2 Revoluções', subtopic: '2.3 Revoluções contemporâneas', description: 'Conceitos e características.', incidence: 'Média' },
  { id: 'hm-2.4', subject: 'História Mundial', topic: '2 Revoluções', subtopic: '2.4 Anarquismo', description: 'Princípios e impactos.', incidence: 'Baixa' },
  { id: 'hm-2.5', subject: 'História Mundial', topic: '2 Revoluções', subtopic: '2.5 Socialismo', description: 'Fundamentos e aplicações.', incidence: 'Alta' },
  { id: 'hm-2.6', subject: 'História Mundial', topic: '2 Revoluções', subtopic: '2.6 Revoluções no século XX', description: 'Rússia e China.', incidence: 'Alta' },
  { id: 'hm-2.7', subject: 'História Mundial', topic: '2 Revoluções', subtopic: '2.7 Revoluções na América Latina', description: 'México e Cuba.', incidence: 'Alta' },
  { id: 'hm-3.1', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.1 Modelos e interpretações', description: 'Teorias das relações internacionais.', incidence: 'Alta' },
  { id: 'hm-3.2', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.2 Concerto Europeu', description: 'Crise (1815-1918).', incidence: 'Média' },
  { id: 'hm-3.3', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.3 Rivalidades coloniais', description: 'Conflitos coloniais.', incidence: 'Média' },
  { id: 'hm-3.4', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.4 Primeira Guerra Mundial', description: 'Causas.', incidence: 'Alta' },
  { id: 'hm-3.5', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.5 14 pontos de Wilson', description: 'Impactos.', incidence: 'Média' },
  { id: 'hm-3.6', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.6 Paz de Versalhes', description: 'Ordem mundial (1919-1939).', incidence: 'Alta' },
  { id: 'hm-3.7', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.7 Liga das Nações', description: 'Papel e limitações.', incidence: 'Alta' },
  { id: 'hm-3.8', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.8 Segunda Guerra Mundial', description: 'Causas.', incidence: 'Alta' },
  { id: 'hm-3.9', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.9 Conferências (Moscou, Teerã, etc.)', description: 'Ordem mundial resultante.', incidence: 'Alta' },
  { id: 'hm-3.10', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.10 Bretton Woods', description: 'Sistema financeiro global.', incidence: 'Alta' },
  { id: 'hm-3.11', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.11 Plano Marshall', description: 'Reconstrução pós-guerra.', incidence: 'Alta' },
  { id: 'hm-3.12', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.12 ONU', description: 'Estrutura e funções.', incidence: 'Alta' },
  { id: 'hm-3.13', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.13 Guerra Fria', description: 'Bipolaridade (Truman a Nixon).', incidence: 'Alta' },
  { id: 'hm-3.14', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.14 Conflitos localizados', description: 'Guerras regionais.', incidence: 'Média' },
  { id: 'hm-3.15', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.15 Détente', description: 'Desescalada de tensões.', incidence: 'Média' },
  { id: 'hm-3.16', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.16 Segunda Guerra Fria', description: 'Reagan-Bush.', incidence: 'Média' },
  { id: 'hm-3.17', subject: 'História Mundial', topic: '3 Relações Internacionais', subtopic: '3.17 Crise do bloco soviético', description: 'Desagregação.', incidence: 'Alta' },
  { id: 'hm-4.1', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.1 Fim do colonialismo do Antigo Regime', description: 'Transformações.', incidence: 'Média' },
  { id: 'hm-4.2', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.2 Nova expansão europeia', description: 'Características.', incidence: 'Alta' },
  { id: 'hm-4.3', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.3 Debates sobre imperialismo', description: 'Natureza do imperialismo.', incidence: 'Média' },
  { id: 'hm-4.4', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.4 Partilha da África e Ásia', description: 'Processos de dominação.', incidence: 'Alta' },
  { id: 'hm-4.5', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.5 Dominação e reação', description: 'Índia, China, Japão.', incidence: 'Alta' },
  { id: 'hm-4.6', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.6 Descolonização', description: 'Processos e impactos.', incidence: 'Alta' },
  { id: 'hm-4.7', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.7 Conferência de Bandung', description: 'Não alinhamento.', incidence: 'Alta' },
  { id: 'hm-4.9', subject: 'História Mundial', topic: '4 Colonialismo e Imperialismo', subtopic: '4.9 Terceiro Mundo', description: 'Conceito e contexto.', incidence: 'Média' },
  { id: 'hm-5.1', subject: 'História Mundial', topic: '5 Evolução Política e Econômica nas Américas', subtopic: '5.1 Expansão territorial nos EUA', description: 'Contexto histórico.', incidence: 'Alta' },
  { id: 'hm-5.2', subject: 'História Mundial', topic: '5 Evolução Política e Econômica nas Américas', subtopic: '5.2 Guerra de Secessão', description: 'Causas e consequências.', incidence: 'Alta' },
  { id: 'hm-5.3', subject: 'História Mundial', topic: '5 Evolução Política e Econômica nas Américas', subtopic: '5.3 Identidades nacionais na América Latina', description: 'Militarismo e caudilhismo.', incidence: 'Média' },
  { id: 'hm-5.4', subject: 'História Mundial', topic: '5 Evolução Política e Econômica nas Américas', subtopic: '5.4 Doutrina Monroe', description: 'Aplicação e política externa dos EUA.', incidence: 'Alta' },
  { id: 'hm-5.5', subject: 'História Mundial', topic: '5 Evolução Política e Econômica nas Américas', subtopic: '5.5 Pan-Americanismo', description: 'Integração nas Américas.', incidence: 'Alta' },
  { id: 'hm-5.6', subject: 'História Mundial', topic: '5 Evolução Política e Econômica nas Américas', subtopic: '5.6 OEA e Tratado do Rio', description: 'Estrutura e funções.', incidence: 'Alta' },
  { id: 'hm-6.1', subject: 'História Mundial', topic: '6 Ideias e Regimes Políticos', subtopic: '6.1 Correntes ideológicas do século XIX', description: 'Liberalismo, nacionalismo.', incidence: 'Média' },
  { id: 'hm-6.2', subject: 'História Mundial', topic: '6 Ideias e Regimes Políticos', subtopic: '6.2 Estados nacionais', description: 'Alemanha e Itália.', incidence: 'Média' },
  { id: 'hm-6.3', subject: 'História Mundial', topic: '6 Ideias e Regimes Políticos', subtopic: '6.3 Correntes ideológicas do século XX', description: 'Democracia, fascismo, comunismo.', incidence: 'Alta' },
  { id: 'hm-6.4', subject: 'História Mundial', topic: '6 Ideias e Regimes Políticos', subtopic: '6.4 Ditaduras e regimes fascistas', description: 'Características.', incidence: 'Alta' },
  { id: 'hm-6.5', subject: 'História Mundial', topic: '6 Ideias e Regimes Políticos', subtopic: '6.5 Novo nacionalismo', description: 'Fundamentalismo contemporâneo.', incidence: 'Média' },
  { id: 'hm-6.6', subject: 'História Mundial', topic: '6 Ideias e Regimes Políticos', subtopic: '6.6 Liberalismo no século XX', description: 'Evolução.', incidence: 'Média' },
  { id: 'hm-7.1', subject: 'História Mundial', topic: '7 Vida Cultural', subtopic: '7.1 Movimento romântico', description: 'Características.', incidence: 'Baixa' },
  { id: 'hm-7.2', subject: 'História Mundial', topic: '7 Vida Cultural', subtopic: '7.2 Cultura do imperialismo', description: 'Influências culturais.', incidence: 'Baixa' },
  { id: 'hm-7.3', subject: 'História Mundial', topic: '7 Vida Cultural', subtopic: '7.3 Vanguardas europeias', description: 'Movimentos artísticos.', incidence: 'Baixa' },
  { id: 'hm-7.4', subject: 'História Mundial', topic: '7 Vida Cultural', subtopic: '7.4 Modernismo', description: 'Contexto cultural.', incidence: 'Média' },
  { id: 'hm-7.5', subject: 'História Mundial', topic: '7 Vida Cultural', subtopic: '7.5 Pós-modernidade', description: 'Características culturais.', incidence: 'Baixa' },
  { id: 'hm-8.1', subject: 'História Mundial', topic: '8 Relações Internacionais no Século XXI', subtopic: '8.1 Paradigmas digitais', description: 'Redes sociais e ferramentas digitais.', incidence: 'Média' },

  // POLÍTICA INTERNACIONAL
  { id: 'pi-1', subject: 'Política Internacional', topic: '1 Relações Internacionais', subtopic: 'Conceitos e atores', description: 'Conceitos, atores, processos, instituições e fluxos.', incidence: 'Alta' },
  { id: 'pi-2', subject: 'Política Internacional', topic: '2 Política Externa Brasileira', subtopic: 'Evolução histórica', description: 'Evolução desde 1945, principais vertentes e linhas conceituais.', incidence: 'Alta' },
  { id: 'pi-3.1', subject: 'Política Internacional', topic: '3 Brasil e América do Sul', subtopic: '3.1 Integração regional', description: 'Processos de integração na região.', incidence: 'Alta' },
  { id: 'pi-3.2', subject: 'Política Internacional', topic: '3 Brasil e América do Sul', subtopic: '3.2 MERCOSUL', description: 'Origens, objetivos, características e estágios de integração.', incidence: 'Alta' },
  { id: 'pi-3.4', subject: 'Política Internacional', topic: '3 Brasil e América do Sul', subtopic: '3.4 Iniciativas de integração', description: 'Física, energética, política, econômica, social e de segurança.', incidence: 'Alta' },
  { id: 'pi-4', subject: 'Política Internacional', topic: '4 Argentina', subtopic: 'Relações bilaterais', description: 'Política externa e relações com o Brasil.', incidence: 'Média' },
  { id: 'pi-5', subject: 'Política Internacional', topic: '5 Relações com o Hemisfério', subtopic: 'América Latina e Caribe', description: 'Relações do Brasil com os demais países da região.', incidence: 'Média' },
  { id: 'pi-6', subject: 'Política Internacional', topic: '6 Estados Unidos', subtopic: 'Relações bilaterais', description: 'Política externa e relações com o Brasil.', incidence: 'Alta' },
  { id: 'pi-7', subject: 'Política Internacional', topic: '7 União Europeia', subtopic: 'Evolução e estrutura', description: 'Origens, evolução, estrutura e política externa europeia.', incidence: 'Alta' },
  { id: 'pi-8', subject: 'Política Internacional', topic: '8 Rússia', subtopic: 'Relações bilaterais', description: 'Política externa e relações com o Brasil.', incidence: 'Média' },
  { id: 'pi-9', subject: 'Política Internacional', topic: '9 África', subtopic: 'Relações bilaterais', description: 'Política externa e relações com o Brasil.', incidence: 'Média' },
  { id: 'pi-10.1', subject: 'Política Internacional', topic: '10 Brasil e Ásia', subtopic: '10.1 China, Índia e Japão', description: 'Políticas externas e relações bilaterais.', incidence: 'Alta' },
  { id: 'pi-11.1', subject: 'Política Internacional', topic: '11 Brasil e Oriente Médio', subtopic: '11.1 Questão israelo-palestina', description: 'Contexto e impactos.', incidence: 'Alta' },
  { id: 'pi-11.2', subject: 'Política Internacional', topic: '11 Brasil e Oriente Médio', subtopic: '11.2 Síria, Iraque e Irã', description: 'Situações nacionais relevantes.', incidence: 'Média' },
  { id: 'pi-12', subject: 'Política Internacional', topic: '12 CPLP', subtopic: 'Comunidade dos Países de Língua Portuguesa', description: 'Estrutura e atuação.', incidence: 'Média' },
  { id: 'pi-13.1', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.1 Multilateralismo', description: 'ONU, grandes conferências e órgãos multilaterais.', incidence: 'Alta' },
  { id: 'pi-13.2', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.2 Desenvolvimento sustentável', description: 'Conceitos e práticas globais.', incidence: 'Alta' },
  { id: 'pi-13.3', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.3 Pobreza e fome', description: 'Ações internacionais de combate.', incidence: 'Média' },
  { id: 'pi-13.4', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.4 Meio ambiente', description: 'Políticas e regimes ambientais globais.', incidence: 'Alta' },
  { id: 'pi-13.5', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.5 Mar, espaço e Antártida', description: 'Questões de governança global.', incidence: 'Média' },
  { id: 'pi-13.6', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.6 Direitos humanos', description: 'Questões de gênero, raça e religião.', incidence: 'Alta' },
  { id: 'pi-13.7', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.7 Migrações', description: 'Migrantes, refugiados e apátridas.', incidence: 'Alta' },
  { id: 'pi-13.8', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.8 Comércio internacional', description: 'OMC e cadeias globais de suprimento.', incidence: 'Alta' },
  { id: 'pi-13.9', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.9 Sistema financeiro internacional', description: 'Estrutura e funcionamento.', incidence: 'Média' },
  { id: 'pi-13.10', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.10 Desarmamento', description: 'Não proliferação e regimes internacionais.', incidence: 'Alta' },
  { id: 'pi-13.11', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.11 Crimes de guerra', description: 'Genocídio, holocausto e Tribunal Penal Internacional.', incidence: 'Média' },
  { id: 'pi-13.12', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.12 Terrorismo', description: 'Contexto e combate internacional.', incidence: 'Alta' },
  { id: 'pi-13.13', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.13 Crime transnacional', description: 'Narcotráfico e crimes cibernéticos.', incidence: 'Média' },
  { id: 'pi-13.14', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.14 Reforma da ONU', description: 'Propostas e debates contemporâneos.', incidence: 'Alta' },
  { id: 'pi-13.15', subject: 'Política Internacional', topic: '13 Brasil e Agenda Internacional', subtopic: '13.15 Operações de paz', description: 'Participação brasileira no sistema ONU.', incidence: 'Alta' },
  { id: 'pi-14.1', subject: 'Política Internacional', topic: '14 Sistema Interamericano', subtopic: '14.1 OEA', description: 'Organização dos Estados Americanos.', incidence: 'Alta' },
  { id: 'pi-15', subject: 'Política Internacional', topic: '15 Blocos Econômicos', subtopic: 'Formação e acordos', description: 'Acordos comerciais e promoção comercial.', incidence: 'Alta' },
  { id: 'pi-16', subject: 'Política Internacional', topic: '16 Segurança na Política Externa', subtopic: 'Dimensão de segurança', description: 'Ações e estratégias de segurança externa.', incidence: 'Alta' },
  { id: 'pi-17', subject: 'Política Internacional', topic: '17 Coalizões Internacionais', subtopic: 'G-20, IBAS e BRICS', description: 'Atuação brasileira em coalizões.', incidence: 'Alta' },
  { id: 'pi-18', subject: 'Política Internacional', topic: '18 Cooperação Sul-Sul', subtopic: 'Iniciativas de cooperação', description: 'Impactos e projetos de cooperação técnica.', incidence: 'Alta' },
  { id: 'pi-19', subject: 'Política Internacional', topic: '19 Diplomacia da Saúde', subtopic: 'Cooperação em saúde', description: 'Iniciativas de cooperação internacional em saúde.', incidence: 'Média' },

  // ECONOMIA
  { id: 'eco-1.1', subject: 'Economia', topic: '1 Microeconomia', subtopic: '1.1 Demanda do Consumidor', description: 'Preferências, equilíbrio, curva de demanda.', incidence: 'Alta' },
  { id: 'eco-1.2', subject: 'Economia', topic: '1 Microeconomia', subtopic: '1.2 Oferta do Produtor', description: 'Fatores de produção, função de produção.', incidence: 'Alta' },
  { id: 'eco-1.3', subject: 'Economia', topic: '1 Microeconomia', subtopic: '1.3 Tipos de Mercados e Bens', description: 'Concorrência perfeita, monopólio, oligopólio.', incidence: 'Alta' },
  { id: 'eco-2.1', subject: 'Economia', topic: '2 Macroeconomia', subtopic: '2.1 Contabilidade Nacional', description: 'Renda, produto, teorias clássica e keynesiana.', incidence: 'Alta' },
  { id: 'eco-2.2', subject: 'Economia', topic: '2 Macroeconomia', subtopic: '2.2 Contas externas', description: 'Déficit, superávit, balanço de pagamentos.', incidence: 'Alta' },
  { id: 'eco-2.3', subject: 'Economia', topic: '2 Macroeconomia', subtopic: '2.3 Economia do Setor Público', description: 'Gastos, receitas, política fiscal, dívida pública.', incidence: 'Alta' },
  { id: 'eco-2.4', subject: 'Economia', topic: '2 Macroeconomia', subtopic: '2.4 Modelo IS-LM-BP', description: 'Estrutura e aplicações.', incidence: 'Alta' },
  { id: 'eco-2.5', subject: 'Economia', topic: '2 Macroeconomia', subtopic: '2.5 Teoria e Política Monetária', description: 'Funções da moeda, oferta e procura, inflação.', incidence: 'Alta' },
  { id: 'eco-2.7', subject: 'Economia', topic: '2 Macroeconomia', subtopic: '2.7 Crescimento e Desenvolvimento', description: 'Teorias de crescimento, inovação, modelos.', incidence: 'Alta' },
  { id: 'eco-2.8', subject: 'Economia', topic: '2 Macroeconomia', subtopic: '2.8 Emprego e Renda', description: 'Desemprego, indicadores, Lei de Okun.', incidence: 'Média' },
  { id: 'eco-3.1', subject: 'Economia', topic: '3 Economia Internacional', subtopic: '3.1 Teorias de Comércio', description: 'Clássicas, neoclássicas, contemporâneas.', incidence: 'Alta' },
  { id: 'eco-3.2', subject: 'Economia', topic: '3 Economia Internacional', subtopic: '3.2 Macroeconomia Aberta', description: 'Fluxos internacionais, regimes de câmbio.', incidence: 'Alta' },
  { id: 'eco-3.3', subject: 'Economia', topic: '3 Economia Internacional', subtopic: '3.3 Instrumentos de Política Comercial', description: 'Tarifas, quotas, subsídios.', incidence: 'Alta' },
  { id: 'eco-4.1', subject: 'Economia', topic: '4 História Econômica Brasileira', subtopic: '4.1 Século XIX', description: 'Economia cafeeira.', incidence: 'Alta' },

  // DIREITO INTERNO
  { id: 'di-1', subject: 'Direito Interno', topic: '1 Normas Jurídicas', subtopic: 'Conceitos e aplicações', description: 'Conceitos e aplicações das normas no ordenamento.', incidence: 'Média' },
  { id: 'di-2', subject: 'Direito Interno', topic: '2 Personalidade Jurídica', subtopic: 'Definição e implicações', description: 'Definição e implicações jurídicas.', incidence: 'Baixa' },
  { id: 'di-3', subject: 'Direito Interno', topic: '3 Constituição', subtopic: 'Teoria da Constituição', description: 'Conceito, classificações, primado e controle de constitucionalidade.', incidence: 'Alta' },
  { id: 'di-4', subject: 'Direito Interno', topic: '4 Estado', subtopic: 'Teoria do Estado', description: 'Elementos, soberania e divisão de competências.', incidence: 'Alta' },
  { id: 'di-5', subject: 'Direito Interno', topic: '5 Estado Democrático de Direito', subtopic: 'Conceito e objetivos', description: 'Conceito, objetivos e divisão de poderes.', incidence: 'Alta' },
  { id: 'di-6', subject: 'Direito Interno', topic: '6 Organização dos Poderes', subtopic: 'Competências', description: 'Competências no Direito Brasileiro.', incidence: 'Média' },
  { id: 'di-7', subject: 'Direito Interno', topic: '7 Processo Legislativo', subtopic: 'Funcionamento', description: 'Funcionamento do processo legislativo no Brasil.', incidence: 'Alta' },
  { id: 'di-8', subject: 'Direito Interno', topic: '8 Direitos e Garantias Fundamentais', subtopic: 'Direitos Fundamentais', description: 'Ordenamento jurídico brasileiro e proteção aos direitos.', incidence: 'Alta' },
  { id: 'di-9', subject: 'Direito Interno', topic: '9 Administração Pública', subtopic: 'Princípios e estrutura', description: 'Princípios, estrutura e atos administrativos.', incidence: 'Média' },
  { id: 'di-10', subject: 'Direito Interno', topic: '10 Licitações e Contratos', subtopic: 'Normas e práticas', description: 'Regime de licitações e contratos administrativos.', incidence: 'Baixa' },
  { id: 'di-11', subject: 'Direito Interno', topic: '11 Responsabilidade Civil do Estado', subtopic: 'Conceitos e aplicações', description: 'Responsabilidade objetiva e subjetiva do Estado.', incidence: 'Média' },
  { id: 'di-12', subject: 'Direito Interno', topic: '12 Servidores Públicos', subtopic: 'Regime jurídico', description: 'Direitos, deveres, improbidade e regime disciplinar.', incidence: 'Baixa' },
  { id: 'di-13', subject: 'Direito Interno', topic: '13 Regime Jurídico do Serviço Exterior', subtopic: 'Lei nº 11.440/2006', description: 'Regime jurídico dos servidores do SEB.', incidence: 'Baixa' },
  { id: 'di-14', subject: 'Direito Interno', topic: '14 Finanças Públicas', subtopic: 'Normas orçamentárias', description: 'Sistema orçamentário e normas financeiras.', incidence: 'Baixa' },


  // DIREITO INTERNACIONAL PÚBLICO
  { id: 'dip-1.1', subject: 'Direito Internacional Público', topic: '1 Natureza e Fundamento', subtopic: '1.1 Sociedade internacional', description: 'Estrutura e evolução.', incidence: 'Alta' },
  { id: 'dip-1.2', subject: 'Direito Internacional Público', topic: '1 Natureza e Fundamento', subtopic: '1.2 Fundamento do DIP', description: 'Teorias voluntaristas e objetivistas.', incidence: 'Alta' },
  { id: 'dip-1.3', subject: 'Direito Internacional Público', topic: '1 Natureza e Fundamento', subtopic: '1.3 DIP e Direito Interno', description: 'Dualismo e monismo.', incidence: 'Alta' },
  { id: 'dip-2.1', subject: 'Direito Internacional Público', topic: '2 Fontes do DIP', subtopic: '2.1 Estatuto da CIJ', description: 'Artigo 38.', incidence: 'Alta' },
  { id: 'dip-2.2', subject: 'Direito Internacional Público', topic: '2 Fontes do DIP', subtopic: '2.2 Tratados', description: 'Conceito, validade e efeitos.', incidence: 'Alta' },
  { id: 'dip-2.3', subject: 'Direito Internacional Público', topic: '2 Fontes do DIP', subtopic: '2.3 Convenção de Viena (1969)', description: 'Direito dos Tratados.', incidence: 'Alta' },
  { id: 'dip-2.4', subject: 'Direito Internacional Público', topic: '2 Fontes do DIP', subtopic: '2.4 Costume internacional', description: 'Elementos e prova.', incidence: 'Alta' },
  { id: 'dip-2.5', subject: 'Direito Internacional Público', topic: '2 Fontes do DIP', subtopic: '2.5 Atos unilaterais', description: 'Natureza e efeitos.', incidence: 'Alta' },
  { id: 'dip-3.1', subject: 'Direito Internacional Público', topic: '3 Sujeitos de DIP', subtopic: '3.1 Estados', description: 'Elementos e soberania.', incidence: 'Alta' },
  { id: 'dip-3.2', subject: 'Direito Internacional Público', topic: '3 Sujeitos de DIP', subtopic: '3.2 Organizações internacionais', description: 'Personalidade e poderes.', incidence: 'Alta' },
  { id: 'dip-3.3', subject: 'Direito Internacional Público', topic: '3 Sujeitos de DIP', subtopic: '3.3 Indivíduo no DIP', description: 'Capacidade e proteção.', incidence: 'Alta' },
  { id: 'dip-4.1', subject: 'Direito Internacional Público', topic: '4 Reconhecimento', subtopic: '4.1 Reconhecimento de Estado', description: 'Teorias e prática.', incidence: 'Alta' },
  { id: 'dip-4.2', subject: 'Direito Internacional Público', topic: '4 Reconhecimento', subtopic: '4.2 Reconhecimento de Governo', description: 'Critérios.', incidence: 'Alta' },
  { id: 'dip-5.1', subject: 'Direito Internacional Público', topic: '5 Responsabilidade Internacional', subtopic: '5.1 Atribuição e ilicitude', description: 'Elementos do fato ilícito.', incidence: 'Alta' },
  { id: 'dip-5.2', subject: 'Direito Internacional Público', topic: '5 Responsabilidade Internacional', subtopic: '5.2 Consequências e reparação', description: 'Formas de reparação.', incidence: 'Alta' },
  { id: 'dip-6.1', subject: 'Direito Internacional Público', topic: '6 Solução de Controvérsias', subtopic: '6.1 Meios diplomáticos', description: 'Negociação, mediação, inquérito.', incidence: 'Alta' },
  { id: 'dip-6.2', subject: 'Direito Internacional Público', topic: '6 Solução de Controvérsias', subtopic: '6.2 Meios jurisdicionais', description: 'Arbitragem e tribunais.', incidence: 'Alta' },
  { id: 'dip-7.1', subject: 'Direito Internacional Público', topic: '7 Imunidades', subtopic: '7.1 Imunidade de jurisdição', description: 'Estado e agentes diplomáticos.', incidence: 'Alta' },
  { id: 'dip-7.2', subject: 'Direito Internacional Público', topic: '7 Imunidades', subtopic: '7.2 Convenções de Viena (1961/1963)', description: 'Relações diplomáticas e consulares.', incidence: 'Alta' },
  { id: 'dip-8.1', subject: 'Direito Internacional Público', topic: '8 Domínio Público Internacional', subtopic: '8.1 Direito do Mar', description: 'Mar territorial, ZEE, Plataforma.', incidence: 'Alta' },
  { id: 'dip-8.2', subject: 'Direito Internacional Público', topic: '8 Domínio Público Internacional', subtopic: '8.2 Espaço aéreo e extra-atmosférico', description: 'Regimes jurídicos.', incidence: 'Média' },

  // DIREITO INTERNACIONAL PRIVADO
  { id: 'dir-1.1', subject: 'Direito Internacional Privado', topic: '1 Introdução', subtopic: '1.1 Objeto e fontes', description: 'Conceito e fundamentação.', incidence: 'Alta' },
  { id: 'dir-2.1', subject: 'Direito Internacional Privado', topic: '2 Conflito de Leis', subtopic: '2.1 Regras de conexão', description: 'LINDB.', incidence: 'Alta' },
  { id: 'dir-2.2', subject: 'Direito Internacional Privado', topic: '2 Conflito de Leis', subtopic: '2.2 Ordem pública', description: 'Limites à aplicação da lei estrangeira.', incidence: 'Alta' },
  { id: 'dir-3.1', subject: 'Direito Internacional Privado', topic: '3 Cooperação Jurídica', subtopic: '3.1 Cartas rogatórias', description: 'Tramitação e exequátur.', incidence: 'Alta' },
  { id: 'dir-3.2', subject: 'Direito Internacional Privado', topic: '3 Cooperação Jurídica', subtopic: '3.2 Homologação de sentença estrangeira', description: 'Requisitos e competência.', incidence: 'Alta' },
  { id: 'dir-4.1', subject: 'Direito Internacional Privado', topic: '4 Nacionalidade e Estrangeiros', subtopic: '4.1 Lei de Migração', description: 'Vistos, expulsão, extradição.', incidence: 'Alta' },

  // GEOGRAFIA
  { id: 'geo-1.1', subject: 'Geografia', topic: '1 História da Geografia', subtopic: '1.1 Expansão colonial', description: 'Pensamento geográfico.', incidence: 'Baixa' },
  { id: 'geo-1.2', subject: 'Geografia', topic: '1 História da Geografia', subtopic: '1.2 Geografia moderna', description: 'Questão nacional na Europa.', incidence: 'Baixa' },
  { id: 'geo-1.3', subject: 'Geografia', topic: '1 História da Geografia', subtopic: '1.3 Correntes teóricas', description: 'Principais correntes da Geografia.', incidence: 'Baixa' },
  { id: 'geo-2.1', subject: 'Geografia', topic: '2 Geografia da População', subtopic: '2.1 Distribuição espacial', description: 'População no Brasil e no mundo.', incidence: 'Alta' },
  { id: 'geo-2.2', subject: 'Geografia', topic: '2 Geografia da População', subtopic: '2.2 Movimentos migratórios', description: 'Internacionais e intranacionais.', incidence: 'Alta' },
  { id: 'geo-2.3', subject: 'Geografia', topic: '2 Geografia da População', subtopic: '2.3 Dinâmica populacional', description: 'Indicadores de qualidade de vida.', incidence: 'Alta' },
  { id: 'geo-3.1', subject: 'Geografia', topic: '3 Geografia Econômica', subtopic: '3.1 Globalização', description: 'Divisão internacional do trabalho.', incidence: 'Média' },
  { id: 'geo-3.2', subject: 'Geografia', topic: '3 Geografia Econômica', subtopic: '3.2 Blocos económicos', description: 'Formação e estrutura.', incidence: 'Alta' },
  { id: 'geo-3.3', subject: 'Geografia', topic: '3 Geografia Econômica', subtopic: '3.3 Energia e logística', description: 'Reordenamento territorial pós-fordista.', incidence: 'Alta' },
  { id: 'geo-3.4', subject: 'Geografia', topic: '3 Geografia Econômica', subtopic: '3.4 Disparidades regionais', description: 'Planejamento no Brasil.', incidence: 'Alta' },
  { id: 'geo-4.1', subject: 'Geografia', topic: '4 Geografia Agrária', subtopic: '4.1 Distribuição geográfica', description: 'Agricultura e pecuária mundiais.', incidence: 'Alta' },
  { id: 'geo-4.2', subject: 'Geografia', topic: '4 Geografia Agrária', subtopic: '4.2 Agronegócio', description: 'Estrutura e funcionamento no Brasil e no mundo.', incidence: 'Alta' },
  { id: 'geo-4.3', subject: 'Geografia', topic: '4 Geografia Agrária', subtopic: '4.3 Estrutura fundiária', description: 'Uso da terra, relações de produção no Brasil.', incidence: 'Alta' },
  { id: 'geo-5.1', subject: 'Geografia', topic: '5 Geografia Urbana', subtopic: '5.1 Urbanização', description: 'Formação de redes de cidades.', incidence: 'Alta' },
  { id: 'geo-5.2', subject: 'Geografia', topic: '5 Geografia Urbana', subtopic: '5.2 Conurbação e metropolização', description: 'Cidades-mundiais.', incidence: 'Alta' },
  { id: 'geo-5.3', subject: 'Geografia', topic: '5 Geografia Urbana', subtopic: '5.3 Dinâmica intraurbana', description: 'Metrópoles brasileiras.', incidence: 'Alta' },
  { id: 'geo-5.4', subject: 'Geografia', topic: '5 Geografia Urbana', subtopic: '5.4 Cidades médias', description: 'Modernização do Brasil.', incidence: 'Alta' },
  { id: 'geo-6.1', subject: 'Geografia', topic: '6 Geografia Politica', subtopic: '6.1 Teorias geopolíticas', description: 'Poder mundial.', incidence: 'Média' },
  { id: 'geo-6.2', subject: 'Geografia', topic: '6 Geografia Politica', subtopic: '6.2 Temas clássicos', description: 'Fronteiras, apropriação política do espaço.', incidence: 'Alta' },
  { id: 'geo-6.3', subject: 'Geografia', topic: '6 Geografia Politica', subtopic: '6.3 Estado e território', description: 'Relações Estado-território.', incidence: 'Média' },
  { id: 'geo-7.1', subject: 'Geografia', topic: '7 Geografia e Gestão Ambiental', subtopic: '7.1 Meio ambiente', description: 'Questões conceituais e institucionais.', incidence: 'Alta' },
  { id: 'geo-7.2', subject: 'Geografia', topic: '7 Geografia e Gestão Ambiental', subtopic: '7.2 Macrodivisão natural', description: 'Biomas, domínios, ecossistemas brasileiros.', incidence: 'Alta' },
  { id: 'geo-7.3', subject: 'Geografia', topic: '7 Geografia e Gestão Ambiental', subtopic: '7.3 Politica e gestão ambiental', description: 'Políticas ambientais no Brasil.', incidence: 'Alta' },
];

export const SUBJECTS = Array.from(new Set(SYLLABUS.map(s => s.subject)));